"""20210802_initial_migration

Revision ID: 163484eaf9bd
Revises: 
Create Date: 2021-08-02 17:39:26.860711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163484eaf9bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_definitions')
    # ### end Alembic commands ###
